language: node_js
node_js: 10.13.0
install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - hugo version
    - rm -rf public
    - npm install

script:
    - hugo --buildFuture
    - gulp
    - echo 'Build done!'
after_success:
    - git config --global user.email "1044032256@qq.com"
    - git config --global user.name "djkloop"
    - git clone https://${ACCESS_TOKEN}@github.com/djkloop/djkloop.cn.git container
    - rm -rf container/*
    - cp -r public/* container
    - ls container
    - cd container
    - git branch -a
    - git status
    - git add .
    - git commit -m 'Travis upate blog'
    - git config --list
    - git push -u origin gh-pages -f
    - curl -d "" ${DEPLOY_API}