---
baseurl: "/"
DefaultContentLanguage: "zh-cn"
hasCJKLanguage: true
languageCode: "zh-cn"
title: "😪"
theme: "hugo-theme-cactus-dark"
metaDataFormat: "yaml"
algolia:
  index: "djkloop.cn"
  key: "e800429610848ec5fd598d3a39bf3bda"
  appID: "YYGTXBRC5Y"
---
